external_components:
  - source: github://GrKoR/esphome_aux_ac_component
    components: [ aux_ac ]
    refresh: 0s
    
esphome:
  name: $devicename
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: 8.8.8.8
    dns2: 1.1.1.1
  reboot_timeout: 0s
  ap:
    ssid: ${upper_devicename} Hotspot
    password: !secret wifi_ap_pass
  use_address: ${wifi_ota_ip}

captive_portal:
debug:

logger:
    level: DEBUG
    # important: for avoiding collisions logger works with UART1 (for esp8266 tx = GPIO2, rx = None)
    hardware_uart: UART1
    baud_rate: 0

api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

# UART0 configuration for aircon communication
uart:
  id: ac_uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 1

sensor:
  - platform: uptime
    name: ${upper_devicename} Uptime Sensor

climate:
  - platform: aux_ac
    name: ${upper_devicename}
    id: ${devicename}
    uart_id: ac_uart_bus
    period: 7s            # период опроса состояния сплита, по дефолту 7 сек
    show_action: true     # надо ли показывать текущий режим работы: при HEAT_COOL mode сплит может греть (HEAT), охлаждать (COOL) или бездействовать (IDLE)
    indoor_temperature:   # сенсор, показывающий температуру воздуха на внутреннем блоке кондиционера; имеет все те же параметры, как и любой сенсор ESPHome
      name: ${upper_devicename} AC Indoor Temperature
      id: ${devicename}_indoor_temp
      internal: false    # сенсор установлен как внутренний по дефолту (не попадёт в Home Assistant)
    visual:
      min_temperature: 16
      max_temperature: 32
      temperature_step: 0.5
    supported_modes:
      - HEAT_COOL   # не AUTO, так как только нагревает и остужает. В доках на ESPHome говорится, что AUTO - это если у устройства есть календарь и какие-то установки по расписанию.
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    custom_fan_modes:
      - MUTE
      - TURBO
    supported_presets:
      - SLEEP
    custom_presets:
      - CLEAN
      - FEEL
      - HEALTH
      - ANTIFUNGUS
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH