external_components:
  - source:
      type: git
      url: https://github.com/Brokly/esphome_aux_ac_component
      #type: local
      #path: my_components     
    components: [ aux_ac ]
    refresh: 0s

esphome:
  name: $devicename
  platform: ESP8266
  board: esp12e

#esp32:
#  board: nodemcu-32s
#  framework:
#    type: arduino
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: !secret gateway 
    subnet: !secret subnet
    dns1: !secret dns1
    dns2: !secret dns2
  ap:
    ssid:  ${upper_devicename} Hotspot
    password: !secret ap_wifi_pass

captive_portal:

debug:

logger:
  level: DEBUG
  baud_rate: 0

api:
    password: !secret api_pass

ota:
    password: !secret ota_pass

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_pass

uart:
  id: ac_uart_bus
  #tx_pin: GPIO16
  #rx_pin: GPIO17
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 1

climate:
  - platform: aux_ac
    name: ${upper_devicename}
    id: aux_id
    uart_id: ac_uart_bus
    period: 7s
    show_action: true
    display_inverted: false
    store_settings: true
    indoor_temperature:
      name: ${upper_devicename} Indoor Temperature
      id: ${low_devicename}_indoor_temp
      internal: false
    outdoor_temperature:
      name: ${upper_devicename} Outdoor Temperature
      id: ${low_devicename}_outdoor_temp
      internal: false
    outbound_temperature:
      name: ${upper_devicename} Colant Outbound Temperature
      id: ${low_devicename}_outbound_temp
      internal: false
    inbound_temperature:
      name: ${upper_devicename} Colant Inbound Temperature
      id: ${low_devicename}_inbound_temp
      internal: false
    strange_temperature:
      name: ${upper_devicename} Strange Temperature
      id: ${low_devicename}_strange_temp
      internal: false
    display_state:
      name: $upper_devicename Display State
      id: ${low_devicename}_display_state
      internal: false
    defrost_state:
      name: $upper_devicename Defrost State
      id: ${low_devicename}_defrost_state
      internal: false
    invertor_power:
      name: $upper_devicename Invertor Power
      id: ${low_devicename}_invertor_power
      internal: false
    visual:
      min_temperature: 16
      max_temperature: 32
      temperature_step: 1
    supported_modes:
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    custom_fan_modes:
      - MUTE
      - TURBO
    supported_presets:
      - SLEEP
    custom_presets:
      - CLEEN
      - HEALTH
      - ANTIFUNGUS
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    update_interval: 30s
    unit_of_measurement: "dBa"
    accuracy_decimals: 0
    
switch:
  - platform: template
    name: $upper_devicename Display
    lambda: |-
      if (id(${low_devicename}_display_state).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - aux_ac.display_on: aux_id
    turn_off_action:
      - aux_ac.display_off: aux_id
